const express = require("express");
const router = express.Router();
const {sendTrendingNerds} = require("../controllers/statistics");
const {searchQueryResponse} = require("../controllers/statistics");
const {sendTrendingTopics} = require("../controllers/statistics");
const {sendTrendingPosts} = require("../controllers/statistics");
const {getPostById,getMySpaces,getUserInformation} = require("../controllers/statistics");
router.get("/getTrendingNerds/",sendTrendingNerds);
router.get("/search/",searchQueryResponse);
router.get("/getTrendingTopics/",sendTrendingTopics);
router.get("/getTrendingPosts/",sendTrendingPosts);
router.get("/posts/",getPostById);
router.post("/get-user-spaces/",getMySpaces);
router.post("/get-user-information",getUserInformation);
module.exports = router;